components {
  id: "Wall"
  component: "/main/Wall/Wall.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Asset 14\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/Wall/Wall.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"wall_box\"\n"
  "  }\n"
  "  data: 220.08\n"
  "  data: 228.38615\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
